Reservation forms ddfsoeg 210
danskernesdigitalebibliotek/dpl-design-system pull request #137
Opened 2022-09-10 22:03 UTC by spaceo

2022-09-12 13:05 UTC, kasperg requested changes
:+1: Good stuff here.

I have a few issues I would like you to look into.

2022-09-12 13:05 UTC, kasperg commented on src/stories/Blocks/reservation/reservation.scss
> +  }
Please ensure that this will also work on mobile.

To me it seems as if 45% width will become quite narrow on mobile devices.

2022-09-14 09:47 UTC, spaceo commented on src/stories/Blocks/reservation/forms/Collect.tsx
> +          { title: "Københavns hovedbibliotek", href: "" },
Good point!

2022-09-15 06:56 UTC, kasperg approved these changes
:+1: LGTM

2022-09-15 08:07 UTC, sinejespersen approved these changes

2022-09-15 09:15 UTC, merged