Add FacetBrowser + .modal--no-padding + make disclosure icon optional
danskernesdigitalebibliotek/dpl-design-system pull request #153
Opened 2022-10-17 14:46 UTC by kasperbirch1

The following has been added
- FacetBrowser + FacetBrowser story  a component that contains everything that needs to be used to display a facet browser modal
- FacetBrowserTag has an onClick that toggles the ccs class facet-browser-tag--selected
- Facet browser dummy data a list of facet groups and their tags retrieved from facet-browser-dummy-data.ts

Other changes
- Make disclosure icon optional This is because we should not have an icon in the facet browser disclosure
- Add  ccs class .modal--no-padding  Since disclosures in the facet browser must go out to the edge, we need to be able to neutralize padding on the modal

2022-10-18 13:08 UTC, Adamik10 requested changes
Good stuff :))) Got a couple of comments and questions here

2022-10-18 13:08 UTC, Adamik10 commented on src/stories/Library/Modals/modal-facet-browser/facet-browser.scss
> +.facet-browser-show-results-btn {
An element inside the .facet-browser block? 
```
&__show-results-btn { ... }
```

2022-10-19 14:07 UTC, Adamik10 approved these changes
Lovely! Good stuff, Kasper.
I am approving this, but I left one comment in regards to the disclosure scss. Please address it before merging 😉

2022-10-19 14:07 UTC, Adamik10 commented on src/stories/Library/disclosure/disclosure.scss
> +  &.disclosure--no-header-padding .disclosure__headline {
In this case I think it makes more sense defining a modifier on the headline element.
So something like:
```
&__headline {
     xyz
     &.disclosure__headline--no-padding {
          your code
     }
}
```

2022-10-24 10:05 UTC, sinejespersen approved these changes

2022-10-25 11:18 UTC, merged