Move logic to show modal into the Modal component
danskernesdigitalebibliotek/dpl-design-system pull request #154
Opened 2022-10-18 10:59 UTC by kasperbirch1

- Move logic to show modal into the Modal component
All the logic for toggle css class .modal-show is now collected in the component. it means that changes only have to take place in one place and that the various components become more readable

- Rename and move .modal-backdrop to its own css class
Since it is not an element but a block by itself, it must have its own css class

2022-10-18 14:18 UTC, Adamik10 requested changes
Very nice initiative! :)) 
I couldn't find anything that stood out. Great job :)

2022-10-18 14:20 UTC, Adamik10 approved these changes
✅

2022-10-23 18:35 UTC, sinejespersen commented on src/stories/Library/Modals/Modal.tsx
> +  const [shoudShowModal, setShouldShowModal] = useState(shownModal);
```suggestion
  const [shouldShowModal, setShouldShowModal] = useState(shownModal);
```

2022-10-23 18:37 UTC, sinejespersen approved these changes
there is a spelling error - if you feel like fixing it go ahead - I approved because it is just a spelling error :)

2022-10-24 08:10 UTC, merged