Feature/links and boxes
danskernesdigitalebibliotek/dpl-design-system pull request #181
Opened 2023-01-09 07:29 UTC by sinejespersen

#### Link to issue

https://jira.itkdev.dk/browse/CMN-448

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-01-09 09:29 UTC, jeppekroghitk approved these changes

2023-01-10 13:29 UTC, spaceo commented on src/stories/Library/Lists/list-reservation/list-reservation.scss
> +  &:hover {
is it not possible to write?:
```
 &:hover,  &:focus  {

2023-01-10 13:31 UTC, spaceo commented on src/stories/Library/Lists/list-reservation/list-reservation.scss
>  }
Seems like the exact same thing that is done in[ search result items](https://github.com/danskernesdigitalebibliotek/dpl-design-system/blob/f3c0e9c4b545e4064fbe7f8f19af4b69234d03df/src/stories/Library/search-result-item/search-result-item.scss#L22-L36).
How about transforming it into a mixin?

2023-01-10 13:32 UTC, spaceo requested changes
Looks good. A few commentz

2023-01-11 12:56 UTC, merged