Feature/5464 recommender
danskernesdigitalebibliotek/dpl-design-system pull request #190
Opened 2023-01-26 11:26 UTC by sinejespersen

#### Link to issue

https://platform.dandigbib.org/issues/5464

#### Description

Add recommender design

#### Screenshot of the result

<img width="907" alt="image" src="https://user-images.githubusercontent.com/15377965/214823588-d68438aa-55b5-4f11-b71b-fc10c3b3509f.png">

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-01-27 12:52 UTC, spaceo commented
The are changes here possibly affecting the campaign. Have you checked if it is your changes that are triggering the Chromatic alarm?

2023-01-27 13:53 UTC, spaceo requested changes
Looks good. I have one comment about organizing BEM in sass.

2023-01-31 19:54 UTC, sinejespersen commented on src/stories/Library/recommender/recommender.scss
> +.recommender--bright {
done

2023-02-15 13:56 UTC, jeppekroghitk approved these changes

2023-02-16 14:08 UTC, spaceo approved these changes
LGTM 👍

2023-02-16 19:25 UTC, merged