Add css for 'expand-icon' in horizontal-term-line
danskernesdigitalebibliotek/dpl-design-system pull request #199
Opened 2023-02-09 10:01 UTC by kasperbirch1

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-02-17 15:20 UTC, kasperg requested changes
Based on the Chromatic changes adding this button increases the line height of the horizontal term lines from 24 to 26px. While minor I do not think that change is intentional.

It seems as if it is added because the `button` element which has default padding in the browser.

One way to approach this would be remove this in our `reset.scss`. That might have other consequences but in general buttons should get their sizing from `button.scss`.

You could also add a new button element to the horizontal term line block.

2023-02-17 15:20 UTC, kasperg commented on src/stories/Library/disclosure/disclosure.scss
> +    &--expanded {
:+1:

2023-02-17 15:22 UTC, kasperg commented on src/stories/Library/disclosure/disclosure.scss
> +      transition: transform 0.3s ease-in-out;
:+1: Nice with a little animation

2023-02-24 13:05 UTC, kasperg approved these changes
:+1: LGTM

It is worth noting that the padding reset on button CSS results in a few layout shifts for link and favourite buttons. None of the seem to be intentional but on the other hand the current padding does not seem to be intentional either.

If we think it is important to reinstate these paddings they could be added to their respective elements e.g. `button-link` and `button-favourite`. I do not think so myself.

2023-03-01 07:20 UTC, jeppekroghitk approved these changes

2023-03-01 07:56 UTC, merged