Refactor headings tree structure for `Material Page`
danskernesdigitalebibliotek/dpl-design-system pull request #206
Opened 2023-03-09 15:15 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFSOEG-452
https://reload.atlassian.net/browse/DDFSOEG-422
https://reload.atlassian.net/browse/DDFSOEG-423

#### This PR is refactoring the headings tree structure for the `Material Page`
To improve user navigation and content comprehension

#### Screenshot of the result
<img width="166" alt="Skærmbillede 2023-03-09 kl  16 02 57" src="https://user-images.githubusercontent.com/49920322/224068035-92d67d71-863b-4d09-b0a8-df003f758576.png">

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

2023-03-09 15:41 UTC, kasperg requested changes
Good job with the screenshot but your work on disclosures needs more thought.

2023-03-09 15:41 UTC, kasperg commented on src/stories/Library/disclosure/Disclosure.tsx
> +        <h2
The disclosure story is used multiple places in the design system and it seems like a stretch to assume that h2 is the right heading level everywhere in the deisgn

I think we need some way to control this from the outside. Here is a seemingly simple way to achieve this using a prop: https://dev.to/s_aitchison/psa-stop-hard-coding-heading-levels-in-your-react-components-2ekp. Note that it probably has to be adjusted to TypeScript and our use case.

2023-03-17 14:11 UTC, jeppekroghitk approved these changes

2023-03-20 08:21 UTC, kasperg approved these changes
:+1: LGTM.

Please look into a final comment/change passing this along.

2023-03-20 08:21 UTC, kasperg commented on src/stories/Library/disclosure/Disclosure.tsx
> +  headingLevel?: HeadingLevelType;
Please make the heading level required.

[The argumentation is the same as for the React components](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/387#discussion_r1135104177).

2023-03-20 10:17 UTC, merged