Feature/5409-favorites-list-material-component
danskernesdigitalebibliotek/dpl-design-system pull request #207
Opened 2023-03-13 08:26 UTC by jeppekroghitk

#### Link to issue

Please add a link to the issue being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My complies with [our coding guidelines](../docs/code_guidelines.md).
- [ ] My code passes our static analysis suite. If not then I have added a comment explaining why this change should be exempt from the code standards and process.
- [ ] My code passes our continuous integration process. If not then I have added a comment explaining why this change should be exempt from the code standards and process.

#### Additional comments or questions

If you have any further comments or questions for the reviewer them please add them here.

2023-03-23 13:43 UTC, spaceo commented on src/stories/Library/favorites-list-material-component/favorites-list-material-component.scss
> +  }
```suggestion
  &__title {
    text-align: center;
    padding: $s-lg;

     &--left {
        text-align: left;
      }
  
    @include breakpoint-m {
      padding-bottom: $s-6xl;
    }
  }
 
```

2023-03-23 13:44 UTC, spaceo commented on src/stories/Library/favorites-list-material-component/favorites-list-material-component.scss
> +    right: 10px;
Is it possible to use spacing variables here?

2023-03-23 13:45 UTC, spaceo commented on src/stories/Library/favorites-list-material-component/favorites-list-material-component.scss
> +    margin-top: 10px;
Is it possible to use a spacing variable here?

2023-03-23 13:45 UTC, spaceo commented on src/stories/Library/favorites-list-material-component/favorites-list-material-component.scss
> +    bottom: 10px;
Is it possible to use spacing variables here?

2023-03-24 12:50 UTC, jeppekroghitk commented on src/stories/Library/favorites-list-material-component/favorites-list-material-component.tsx
> +            </div>
As there is a mix between whole classes, im not sure a function would ease the overview much.

The already merged recommender uses the same approach, see https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/190/files#diff-ec62aa3816e4093dec9c5c3c0663531350b6deafff378e048c9118eb8664264f
so i do not see this being a change request as much as a comment, but i added a TODO for it.

2023-03-29 11:12 UTC, spaceo requested changes
@jeppekroghitk Sorry if I was not precise enough in my review but when I talked about spacing variables I actually meant these:
https://github.com/danskernesdigitalebibliotek/dpl-design-system/blob/873c3a33a08bc91202e72a04ab7f1d958b20c770/src/stories/Library/spacing/spacing.scss#L17-L27
The idea is that by using them it will be possible to adjust the whole design if we find eg. the medium spacing should be smaller or greater than the present value. Then the whole design will change accordingly.

2023-04-12 11:15 UTC, merged