Group modal card skeletons
danskernesdigitalebibliotek/dpl-design-system pull request #489
Opened 2024-02-07 13:06 UTC by Adamik10

#### Link to issue
https://reload.atlassian.net/browse/DDFLSBP-427

#### Description
This PR introduces group modal item skeletons with styling and a brand new story.

#### Screenshot of the result
![image](https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/28546954/540419a8-76e9-4104-88bc-ebf568d21c63)

#### Additional comments or questions
-

2024-02-08 19:19 UTC, spaceo commented on src/stories/Library/Lists/list-dashboard/list-dashboard-skeleton.scss
> +// the skeleton components' dimensions the same as the actual components.
👍 For comment!

2024-02-08 19:21 UTC, spaceo requested changes
Why not having skeleton screens in the header of the modal?
As far as I can see we have external data there as well.
![image](https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/998889/b0d4960a-6753-4cc7-a9af-8ff78f0aec3c)

2024-02-09 09:26 UTC, Adamik10 commented
@spaceo I have been testing it with the lowest possible network throttling option selected (in react), and those parts of the modal must already be loaded when the modal is created. So I didn't want to spend time on something that wouldn't really make a difference in the end.

2024-02-13 08:47 UTC, spaceo approved these changes
LGTM 👍

2024-02-13 10:11 UTC, merged