Refactor link styling in `ListDescription` component
danskernesdigitalebibliotek/dpl-design-system pull request #547
Opened 2024-03-11 19:04 UTC by kasperbirch1

#### Link to issue
https://reload.atlassian.net/browse/DDFFORM-404

#### Description

This pull request refactors the link styling in the ListDescription component. It adds correct link markup and styles the link according to the Drupal rendering method.

https://github.com/danskernesdigitalebibliotek/dpl-react/blob/develop/src/components/material/MaterialDetailsList.tsx
I have looked in the dpl-react component `ListDescription`component and there is no link rendered, so I am not sure if I should change it there?

2024-03-13 14:18 UTC, kasperg requested changes

2024-03-13 14:18 UTC, kasperg commented on src/stories/Library/Lists/list-description/list-description.scss
> +  .link-tag,
As I see it we should drop using *and* supporting `link-tag` for description elements that are not links.

Using nested elements is against our BEM structure and it is just odd to have something that looks like an interactive element but is not.

I think you need to clear this with the LSBP team before proceeding.

2024-03-15 12:43 UTC, Adamik10 reviewed
I tried looking through the links, but I'm still not sure exactly which element we're talking about from the connected Figma screen (link in the ticket).
But I agree with @kasperg that if the element isn't interactive, it shouldn't give off that impression to the end user.

2024-03-22 09:42 UTC, kasperbirch1 commented
@Adamik10 
> I tried looking through the links, but I'm still not sure exactly which element we're talking about from the connected Figma screen (link in the ticket). But I agree with @kasperg that if the element isn't interactive, it shouldn't give off that impression to the end user.

Its in the material details 
https://www.figma.com/file/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?type=design&node-id=8513-62957&mode=design&t=cYSDsVc2dSgBTcoc-4

2024-04-16 07:52 UTC, kasperg commented
@kasperbirch1 I am reassigning to you to decide how to move this forward.

2024-06-04 12:06 UTC, closed without merging