Feature/autosuggest material
danskernesdigitalebibliotek/dpl-design-system pull request #67
Opened 2022-06-13 14:57 UTC by Adamik10

#### Link to issue
![image](https://user-images.githubusercontent.com/28546954/173826228-7ad0ff1e-3335-4499-a1da-ccc459aa94ce.png)
![image](https://user-images.githubusercontent.com/28546954/173827189-c0324a8c-e1f6-4524-8fd4-0156f6960a58.png)

#### Description
Autosuggest-material is a subcomponent of the autosuggest component used to display material suggestions in an autosuggest dropdown. Here is a link to the Figma design file for [desktop](https://www.figma.com/file/ETOZIfmgGS1HUfio57SOh7/S%C3%B8gning?node-id=4709%3A24976), and [mobile](https://www.figma.com/file/ETOZIfmgGS1HUfio57SOh7/S%C3%B8gning?node-id=1749%3A17989) version of the component.

#### Screenshot of the result
Desktop: 
![image](https://user-images.githubusercontent.com/28546954/173827395-0b20b9af-5c69-4c44-a1d3-7a61078a145d.png)

Mobile: 
![image](https://user-images.githubusercontent.com/28546954/173827571-0b24bbf6-dab2-4534-8195-94567130d623.png)

#### Additional comments or questions
What do you think of the solution and of the implementation?

2022-06-16 09:29 UTC, spaceo requested changes
Look great! I have a few comments ;)

2022-06-16 09:29 UTC, spaceo commented on src/stories/autosuggest-material/AutosuggestMaterial.tsx
> +      <li className="autosuggest__item--text text-body-medium-regular">
Do something

2022-06-16 09:29 UTC, spaceo commented on src/stories/autosuggest-text/AutosuggestText.tsx
> +          <li className="autosuggest__item--text text-body-medium-regular">
Do something here as well?

2022-06-16 09:29 UTC, spaceo commented on src/stories/autosuggest-text/autosuggest-text.scss
> +  padding-bottom: 10px;
We dont have fixed spacing variables?

2022-06-16 09:29 UTC, spaceo commented on src/stories/autosuggest-text/autosuggest-text.scss
> +      padding: 0 23px;
Dont we have fixed spacing variables?

2022-06-16 09:55 UTC, Adamik10 commented on src/stories/autosuggest-text/autosuggest-text.scss
> +      padding: 0 23px;
yes! :) gotcha

2022-06-16 11:25 UTC, Adamik10 commented on src/stories/autosuggest-material/AutosuggestMaterial.tsx
> +      <li className="autosuggest__item--text text-body-medium-regular">
roger that! :)

2022-06-16 11:26 UTC, Adamik10 commented on src/stories/autosuggest-text/AutosuggestText.tsx
> +          <li className="autosuggest__item--text text-body-medium-regular">
yes yes :)

2022-06-16 12:06 UTC, spaceo approved these changes

2022-06-18 11:44 UTC, Adamik10 commented on src/stories/autosuggest-material/AutosuggestMaterial.stories.tsx
> +          cover: "https://imgcdn.saxo.com/_9780345514400/0x500",
Oh yes, for sure :) I just felt they didn't really inspire me.

2022-06-18 11:53 UTC, Adamik10 commented on src/stories/autosuggest-material/AutosuggestMaterial.tsx
> +      <ul className="autosuggest__materials">
That's very correct! Thanks ❤️ I fixed it

2022-06-18 12:14 UTC, Adamik10 commented on src/stories/autosuggest-material/AutosuggestMaterial.tsx
> +                <div className="autosuggest__materials__item__content__cover">
Haha yes! I followed this article to fix it: https://scalablecss.com/bem-nesting-grandchild-elements/

2022-06-20 07:12 UTC, sinejespersen approved these changes

2022-06-20 07:34 UTC, cableman requested changes
I don't think we should add covers to the repositories (also we don't have the copyright to the covers?)

2022-06-28 13:28 UTC, cableman approved these changes

2022-06-28 13:33 UTC, merged