DDFLSBP-659 - Add visual indicators on required fields
danskernesdigitalebibliotek/dpl-design-system pull request #681
Opened 2024-07-10 08:51 UTC by Dresse

#### Link to issue

https://reload.atlassian.net/browse/DDFLSBP-659

#### Description

Added styling for required fields. We simply add a new class `.form-required::after` containing an asterisk (*). The class is added on fields where the input field is required to be filled out.

#### Screenshot of the result

Showing the contact webform with required fields:

![Screenshot 2024-07-10 at 10 50 12](https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/6142323/afab0aa4-7e36-46f4-b77a-aae3429943a3)

2024-07-10 12:45 UTC, Dresse commented
@kasperg What is the reason for assigning me back and removing the other assignees? 😄

2024-07-11 14:54 UTC, kasperg requested changes

2024-07-12 14:09 UTC, Dresse commented on src/stories/Library/input-label/input-label.scss
> +}
I have updated the PR with the following:
1. Changed the styling to fit our BEM structure as requested.
2. Updated the existing InputLabel story with an required input label version.
3. I have added a space before the asterisk. For this reason I have also updated input labels in dpl-react with a space, so it is consistent everywhere. PR can be found as part of this PR description and here: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1327

2024-08-19 09:46 UTC, Adamik10 approved these changes
Great stuff 👏

2024-09-02 12:53 UTC, merged