Feature/material header
danskernesdigitalebibliotek/dpl-design-system pull request #81
Opened 2022-07-05 06:24 UTC by kasperbirch1

2022-07-06 15:48 UTC, Adamik10 requested changes
Good job :) I have a couple of comments.

2022-07-06 15:48 UTC, Adamik10 commented on src/stories/material-app/material-app.scss
> +  // source can not be empty
lovely with the comment :)

2022-07-06 15:48 UTC, Adamik10 commented on src/stories/material-header/material-header.tsx
> +          <AvailabilityLabel
I guess we could just map through an array of four values like they do it in Checkbox.stories.tsx
Check that one out ;)

2022-07-06 15:48 UTC, Adamik10 commented on src/stories/material-header/material-periodikum-select.scss
> +.material-periodikum-container {
Same thing with the -container as the other comment. Do we need the suffix?

2022-07-06 15:48 UTC, Adamik10 commented on src/stories/material-header/material-periodikum-select.tsx
> +            <option value="">2022</option>
Can we instead loop over an object of values here?

2022-07-07 07:11 UTC, Adamik10 approved these changes
🥇

2022-07-07 07:21 UTC, sinejespersen approved these changes

2022-07-07 10:43 UTC, merged